### ISSUE TITLE
Manifest is broken

### ISSUE THREAD

**Issue by jabuxas** [an-anime-team/aagl-ebuilds#16]
Portage is complaining about 2.3.9 in manifest but no ebuild available for 2.3.9
![image](https://user-images.githubusercontent.com/94939040/193469004-8c40d0be-0cda-4ca2-9b6f-0fd89e18d6da.png)

Removing 2.3.9 from the manifest made me able to emerge the 2.4.0 version. To be honest I don't know much about ebuilds and Manifest but I think what I did was the right thing. Hopefully it was indeed something that was forgotten or else i'm just making a fool of myself.

**Comment by natimerry** [comment]
#17 seems to have fixed the Manifest file and deleted entries for older ebuilds.
Re-sync the overlay to fix the issue.

**Comment by jabuxas** [comment]
Fixed.
