### ISSUE TITLE
Protect main branch, limit users with write access

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/aagl-ebuilds#4]
Please protect the main branch of this repo to prevent accidental pushes to it.
(e.g. https://github.com/an-anime-team/aagl-ebuilds/pull/3#issuecomment-1243473424, without the intent to put him to the pillory)
 In git you can always roll back and change history, but for our users this means additional trouble. Portage can not rebase a repository when syncing it with `emerge --sync` (or `emaint`), there is only fast forward. So the users have to delete the files in `/var/db/repos/The-Anime-Game` manually and then sync again or do some manual git commands on that repo. 

For our users updates should go smooth without manual interventions.

**Comment by Mar0xy** [comment]
This is limited by default but krypton simply gave him access to this repo after he asked. I have removed his maintain access for now

**Comment by Schievel1** [comment]
No, I actually did not mean him in particular.

Github has the option to protect the main branch. Then you can not push to main, always need to merge a branch to move commits into main. Can you set this up?

**Comment by Mar0xy** [comment]
Ah, you mean the protection rules in general.

The thing you said does not exist this is probably similar but most def not what you are looking for

![image](https://user-images.githubusercontent.com/8841466/190002734-3fdadce2-55d9-486a-92c4-d068827bb8f4.png)

**Comment by Schievel1** [comment]
> Ah, you mean the protection rules in general.
> 
> The thing you said does not exist this is probably similar but most def not what you are looking for
> 
> ![image](https://user-images.githubusercontent.com/8841466/190002734-3fdadce2-55d9-486a-92c4-d068827bb8f4.png)

No this is exactly what I mean "Require a pull request before merging". Do this for main please. This should work when you put in `main` as naming rule. It can use wildcards, but thats not necessary I think. 
This way we can not accidetaly push onto main an break user setups.

**Comment by Mar0xy** [comment]
I created the rule now.
